### ISSUE TITLE
Java jar issue

### ISSUE THREAD

**Issue by gopinath6** [bit4woo/domain_hunter#2]
Any plan to provide jar for java 1.7 version?

Getting below error when trying to add in burp 

java.lang.UnsupportedClassVersionError: burp/BurpExtender : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at burp.sue.a(Unknown Source)
	at burp.sue.<init>(Unknown Source)
	at burp.mn.a(Unknown Source)
	at burp.ooh.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
The extension could not be loaded because it requires a later version of Java. To use this extension you will need to start Burp with the required or later Java version.

**Comment by bit4woo** [comment]
I write this extender on Java1.8, hope you to update your JDK. No plan to support lower version.thanks
